# installing httpd in nodes

---
- name: update n2
  hosts: n2
  become: yes

  tasks:
  - name: ensure httpd installed
    yum:
     name: httpd
     state: present

  - name: ensure httpd started
    service:
     name: httpd
     state: started 

  - name: ensure httpd enebled
    service:
     name: httpd
     enabled: yes 
...

