# installing httpd and apache2 in nodes

---
- name: update n2
  hosts: all
  become: yes

  tasks:
  - name: ensure httpd installed
    yum:
     name: httpd
     state: present
    when: ansible_distribution == "CentOS"

  - name: ensure httpd started
    service:
     name: httpd
     state: started 
    when: ansible_distribution == "CentOS"


  - name: ensure httpd enebled
    service:
     name: httpd
     enabled: yes 
    when: ansible_distribution == "CentOS"

  - name: ensure apache2 installed
    apt:
     update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: ensure apache2 installed
    apt:
     name: apache2
     state: present 
    when: ansible_distribution == "Ubuntu"

  - name: ensure apache2 started
    service:
     name: apache2
     state: started
    when: ansible_distribution == "Ubuntu"

  - name: ensure apache2 enabled
    service:
      name: apache2
      enabled: yes 
    when: ansible_distribution == "Ubuntu"

...

